emacs -batch vhdl/uvm/classes/philosophers/ntm_philosophers_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/classes/soldiers/ntm_soldiers_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/classes/workers/ntm_workers_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/advanced_computer_architecture/multi_processor_system_on_chip/multi_processor_system_on_chip_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/advanced_computer_architecture/processing_unit/mimd_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/advanced_computer_architecture/processing_unit/misd_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/advanced_computer_architecture/processing_unit/simd_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/advanced_computer_architecture/processing_unit/sisd_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/advanced_computer_architecture/system_on_chip/bus_on_chip_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/advanced_computer_architecture/system_on_chip/network_on_chip_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/computer_architecture/harvard_architecture/alu_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/computer_architecture/harvard_architecture/control_unit_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/computer_architecture/harvard_architecture/io_unit_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/computer_architecture/harvard_architecture/memory_unit_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/computer_architecture/von_neumann_architecture/alu_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/computer_architecture/von_neumann_architecture/control_unit_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/computer_architecture/von_neumann_architecture/io_unit_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/computer_architecture/von_neumann_architecture/memory_unit_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/bit/bit_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/combinational_logic/arithmetic_circuits_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/combinational_logic/arithmetic_circuits.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/combinational_logic/logic_circuits_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/combinational_logic/logic_circuits.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/finite_state_machine/finite_state_machine_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/logic_gate/and_gate_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/logic_gate/nand_gate_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/logic_gate/nor_gate_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/logic_gate/not_gate_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/logic_gate/or_gate_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/logic_gate/xnor_gate_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/logic_gate/xor_gate_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/logic_gate/yes_gate_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/information/pushdown_automaton/pushdown_automaton_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/neural_network/feedforward_neural_network/feedforward_neural_network_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/neural_network/long_short_term_memory_neural_network/long_short_term_memory_neural_network_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/neural_network/transformer_neural_network/transformer_neural_network_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/turing_machine/differentiable_neural_computer/feedforward_differentiable_neural_computer_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/turing_machine/differentiable_neural_computer/lstm_differentiable_neural_computer_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/turing_machine/differentiable_neural_computer/transformer_differentiable_neural_computer_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/turing_machine/neural_turing_machine/feedforward_neural_turing_machine_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/turing_machine/neural_turing_machine/lstm_neural_turing_machine_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
emacs -batch vhdl/uvm/computing/turing_machine/neural_turing_machine/transformer_neural_turing_machine_testbench.vhd -f vhdl-beautify-buffer -f save-buffer
